// Fetches all Notion icon slugs from https://www.notion.so/icons/all
// and writes a curated subset to src/notion-icons.ts.
//
// Usage: pnpm tsx scripts/generate-notion-icons.ts
//
// The curated list is hand-picked for visual distinctness on a kanban board.
// Icons that are inappropriate, too niche, or visually similar are excluded.
// To update the list, edit CURATED_SLUGS below and re-run.

const CURATED_SLUGS = [
  // Code & dev
  'code', 'code-scan', 'command-line', 'bug', 'git', 'branch', 'branch-create',
  'branch-fork', 'branch-merge', 'pull-request', 'database', 'server',
  'computer', 'computer-chip', 'laptop', 'mobile', 'tablet',
  'extension', 'dependency', 'snippet', 'merge',

  // Tools & work
  'gear', 'gears', 'hammer', 'wrench', 'magic-wand', 'screwdriver',
  'paint-brush', 'pencil', 'pen', 'ruler', 'crop', 'cut',
  'light-bulb', 'flashlight', 'magnet', 'key', 'key-antique',
  'lock', 'lock-keyhole', 'shield', 'safety-pin',

  // Data & charts
  'chart', 'chart-alternate', 'chart-area', 'chart-donut', 'chart-line',
  'chart-mixed', 'chart-pie', 'activity', 'dashboard', 'formula',
  'mathematics', 'science', 'chemistry', 'microscope', 'telescope',

  // Shapes & abstract
  'circle', 'circle-alternate', 'circle-dashed', 'hexagon', 'hexagon-alternate',
  'pentagon', 'pentagon-alternate', 'square', 'square-alternate',
  'triangle', 'triangle-alternate', 'octagon', 'star', 'star-outline',
  'gem', 'token', 'orbit',

  // Objects
  'rocket', 'ringed-planet', 'compass', 'target', 'bullseye',
  'fire', 'flash', 'bookmark', 'bookmark-outline', 'flag', 'flag-pennant',
  'puzzle', 'robot', 'ghost', 'gift', 'package', 'tag', 'layers',
  'calendar', 'clock', 'clock-alternate', 'stopwatch', 'hourglass',

  // Navigation & signals
  'location', 'map-pin', 'navigation', 'globe',
  'wifi', 'bluetooth', 'cellular', 'link', 'attachment', 'send',

  // Nature & weather
  'leaf', 'clover', 'clover-four-leaf', 'tree', 'palm-tree',
  'mushroom', 'cactus', 'potted-plant', 'seed',
  'moon', 'sun', 'snowflake', 'rainbow', 'cloud', 'mountains',

  // Animals
  'butterfly', 'bee', 'spider', 'fish', 'crab', 'duck',
  'cat', 'dog', 'hare', 'snake', 'tortoise', 'elephant',

  // Music & media
  'music', 'headphones', 'microphone', 'camera', 'movie',

  // Communication
  'chat', 'mail', 'megaphone', 'bell', 'notification',

  // Files & docs
  'document', 'folder', 'archive', 'list', 'checklist', 'note-eighth',

  // Fun
  'confetti-ball', 'confetti-party-popper', 'balloon', 'jack-o-lantern', 'kite',
  'die1', 'die2', 'die3',
]

const COLORS = [
  'gray',
  'lightgray',
  'brown',
  'yellow',
  'orange',
  'green',
  'blue',
  'purple',
  'pink',
  'red',
] as const

async function main() {
  // Validate slugs against the live Notion icon list
  const res = await fetch('https://www.notion.so/icons/all')
  if (!res.ok) {
    throw new Error(`Failed to fetch icons: ${res.status} ${res.statusText}`)
  }
  const json = (await res.json()) as Record<string, unknown>
  const allSlugs = new Set(Object.keys(json))

  const invalid = CURATED_SLUGS.filter((s) => !allSlugs.has(s))
  if (invalid.length > 0) {
    console.error('Invalid slugs (not found in Notion):', invalid)
    process.exit(1)
  }

  // Deduplicate and sort
  const slugs = [...new Set(CURATED_SLUGS)].sort()

  const output = `// Generated by scripts/generate-notion-icons.ts — do not edit manually.
// Run: pnpm tsx scripts/generate-notion-icons.ts
//
// Curated subset of Notion's native SVG icons (${slugs.length} icons).
// Full catalog: https://www.notion.so/icons/all

export const NOTION_ICON_SLUGS = [
${slugs.map((s) => `  '${s}',`).join('\n')}
] as const

export const NOTION_ICON_COLORS = [
${COLORS.map((c) => `  '${c}',`).join('\n')}
] as const

export type NotionIconSlug = (typeof NOTION_ICON_SLUGS)[number]
export type NotionIconColor = (typeof NOTION_ICON_COLORS)[number]
`

  const fs = await import('node:fs')
  const path = await import('node:path')
  const outPath = path.join(import.meta.dirname, '..', 'src', 'notion-icons.ts')
  fs.writeFileSync(outPath, output)
  console.log(`Wrote ${slugs.length} icon slugs to ${outPath}`)
}

main()
